name: Build and Deploy Azure Web App

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      app-name:
        required: true
        type: string
      publish-profile-dev:
        required: true
        type: string
        description: Base64 encoded publish profile for the dev slot
      publish-profile-prod:
        required: true
        type: string
        description: Base64 encoded publish profile for the production slot
      working-directory:
        required: true
        type: string
        description: The working directory for the project

    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE_DEV:
        required: true
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true

jobs:
  build_web_app:
    name: 🧪 Build Web App
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ inputs.working-directory }}

      - name: Build
        run: dotnet build --no-restore
        working-directory: ${{ inputs.working-directory }}

      - name: Publish
        run: dotnet publish --no-restore -c Release
        working-directory: ${{ inputs.working-directory }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spacegameweb
          path: ${{ inputs.working-directory }}/bin/Release/netcoreapp3.1/publish/

  deployToDev:
    name: 🚀 Deploy to Dev
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == 'refs/heads/development'
    environment: 
      name: deploytodev
      url: https://tailspindemo-dev.azurewebsites.net
    needs: [build_web_app]

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: spacegameweb
          path: .

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: dev
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}

  deployToProd:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    needs: [build_web_app, deployToDev]
    environment: 
      name: deploytoProd
      url: https://tailspindemo.azurewebsites.net

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: spacegameweb
          path: .

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app-name }}
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
