# This is a basic workflow to help you get started with Actions

name: CI-Reusable

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string


jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        token: ${{secrets.PATTOKEN}}
